services:
  amqp:
    container_name: amqp
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s
  add-test-job:
    build:
      context: ./add-test-job/
      dockerfile: Dockerfile
    volumes:
      - ./add-test-job/:/app/
    container_name: add-test-job
    working_dir: /app
    command: bash -c "node ./main.js"
    depends_on:
      amqp:
        condition: service_healthy
  video-auto-composition:
    stop_grace_period: 1s
    depends_on:
      add-test-job:
        condition: service_started
    build: .
    container_name: video-auto-composition
    ports:
      - "5000:5000"
    working_dir: /app
    volumes:
      - ./assets/:/app/assets/
      - ./src/:/app/src/
      - ./templates/:/app/templates/
      - ./app.py:/app/app.py
      - ./queues.py:/app/queues.py
      - ./worker.js:/app/worker.js
    command: bash -c ". venv/bin/activate && node worker.js"
