services:
  video-auto-composition:
    build: .
    container_name: video-auto-composition
    ports:
      - "5000:5000"
    working_dir: /app
    volumes:
      - ./assets/:/app/assets/
      - ./src/:/app/src/
      - ./templates/:/app/templates/
      - ./app.py:/app/app.py
    command: python app.py
