services:
  amqp:
    container_name: amqp
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Web UI
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s
  add-test-job:
    build:
      context: ./add-test-job/
      dockerfile: Dockerfile
    volumes:
      - ./add-test-job/:/app/
    container_name: add-test-job
    working_dir: /app
    command: bash -c "node ./main.js"
    depends_on:
      amqp:
        condition: service_healthy
  video-auto-composition:
    stop_grace_period: 1s
    depends_on:
      add-test-job:
        condition: service_completed_successfully
    build: .
    container_name: video-auto-composition
    ports:
      - "5000:5000"
    working_dir: /app
    volumes:
      - ./assets/:/app/assets/
      - ./src/:/app/src/
      - ./templates/:/app/templates/
      - ./app.py:/app/app.py
      - ./queues.py:/app/queues.py
      - ./test.py:/app/test.py
    # command: bash -c "set -xe ; . venv/bin/activate && python3 app.py"
    # command: celery -A tasks worker --loglevel=INFO
    command: bash -c ". venv/bin/activate && python test.py && celery -A app worker --loglevel=INFO"
