services:
  redis:
    stop_grace_period: 1s
    image: "redis:alpine"
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 1s
      retries: 3
  bullboard:
    stop_grace_period: 1s
    container_name: bullboard
    image: ghcr.io/qtvhao/bull-board-docker:master
    restart: always
    ports:
      - 3000:3000
    environment:
      - REDIS_HOST=redis
    stop_grace_period: 1s
  # 
  add-test-job:
    build:
      context: ./add-test-job/
      dockerfile: Dockerfile
    volumes:
      - ./add-test-job/:/app/
    container_name: add-test-job
    working_dir: /app
    command: bash -c "node ./main.js"
    depends_on:
      redis:
        condition: service_healthy
  video-auto-composition:
    stop_grace_period: 1s
    depends_on:
      add-test-job:
        condition: service_completed_successfully
    build: .
    container_name: video-auto-composition
    ports:
      - "5000:5000"
    working_dir: /app
    volumes:
      - ./assets/:/app/assets/
      - ./src/:/app/src/
      - ./templates/:/app/templates/
      - ./app.py:/app/app.py
      - ./queues.py:/app/queues.py
      - ./worker.js:/app/worker.js
    command: bash -c ". venv/bin/activate && node worker.js"
